---
title: "Capstone data"
output: html_notebook
---

```{r}
library(gtfs2emis)
library(data.table)
library(gtfstools)

```

```{r}
# read GTFS.zip
gtfs_file <- system.file("extdata/usa_det_gtfs.zip", package = "gtfs2emis")
gtfs <- gtfstools::read_gtfs(gtfs_file)

# generate transport model
tp_model <- transport_model(gtfs_data = gtfs,spatial_resolution = 100,parallel = TRUE) 
tp_modelom
```

```{r}
fleet_file <- system.file("extdata/usa_det_fleet.txt", package = "gtfs2emis")

fleet_df <- read.csv(fleet_file)

fleet_df
```

```{r}
colnames(fleet_df)[1]  <- "model_year"
#colnames(fleet_df)[6]  <- "fleet_composition"
#colnames(fleet_df)[5]  <- "veh"
#colnames(fleet_df)[4]  <- "veh_type"

#fleet_df['fleet_composition'] <-fleet_df['fleet_composition']/sum(fleet_df['fleet_composition'])

emi_list <- emission_model(tp_model = tp_model
, ef_model = "ef_usa_moves"
, fleet_data = fleet_df
, pollutant = c('CO',  'CO2',  'CH4')
)
emi_list
```

```{r}
emi_time_dt <- emis_summary(emi_list = emi_list, by = "time")

library("writexl")
write_xlsx(emi_time_dt, 'by_time_brazil.xlsx')
```

```{r}
# process by vehicle
 emi_veh_dt<- emis_summary(emi_list = emi_list,
 by = "vehicle"
  )
emi_veh_dt
write_xlsx(emi_veh_dt, 'by_vehicle_brazil.xlsx')
```


